apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    components: frontend
spec:
  containers:
    - name: app
      image: ghcr.io/zzzhukkk/app_links
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"