app:
  replicas: 1
  components: frontend
  image:
    image_name: ghcr.io/zzzhukkk/app_links
    image_tag: v1.4
  containerport: 80
  resources:
    memory: "128Mi"
    cpu: "200m"

env: test

req:
 value:
   limits:
     memory: "128Mi"
     cpu: "200m"

users:
 - name: vanya
   role: admin
 - name: anton
   role: manager