apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
  DATABASEURL: {{ printf "postgresql://%s:%s@%s-clusterip:%d/%s" .Values.base.user .Values.base.password .Values.postgres.name ( .Values.postgres.containerport | int64 ) .Values.base.db | b64enc | quote }}
