apiVersion: v1
kind: Service
metadata:
  name: app-clusterip
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.app.containerport }}
    protocol: TCP
  selector:
    components: {{ .Values.app.components }}
