apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.base.db | b64enc }}
  POSTGRES_USER: {{ .Values.base.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.base.password | b64enc }}
