apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-deployment
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.postgres.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.postgres.components }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: "{{ .Values.postgres.image.image_name }}:{{ .Values.postgres.image.image_tag }}"
          ports:
            - containerPort: {{ .Values.postgres.containerport }}
          env:
            {{- range .Values.postgres.env }}
            {{- $data := dict "name" $.Values.postgres.name "env" . }}
            {{- include "env.template" $data | indent 12 }}
            {{- end }}
          resources:
            limits: {{ .Values.postgres.resources | toYaml | nindent 14 }}
          volumeMounts:
            - name: {{ .Values.postgres.name }}-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: {{ .Values.postgres.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.name }}-pvc